### ISSUE TITLE
Build package for Tezos

### ISSUE THREAD

**Issue by web-vertalo** [Vertalo/freebsd-ports-public#5]
**Objective**
Build tezos as a FreeBSD package

**Acceptance Criteria**
How will we confirm that this work item is complete?
- [ ] Can build tezos under poudriere
- [ ] Can install via build server

**Tasks**
What will we do to complete this work item?
- [ ] Port Tezos to FreeBSD
- [ ] Configure for poudriere
- [ ] Add to package list for build
- [ ] Build

**Comment by web-vertalo** [comment]
Move to private repo.
